name: Deploy to VPS

on:
  push:
    branches: ['master']
    paths: ['backend/**', '.github/workflows/backend.yml']

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Test
        run: |
          zig build test

      - name: Build
        run: |
          zig build --release=fast

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin
          path: 'backend/zig-out/bin/*'


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v4
        with:
          name: bin
          path: bin

      - name: Upload
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "bin/*"
          target: deploy
          strip_components: 1

      - name: Run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            sudo systemctl stop elothing-api.service
            cp ./deploy/elothing-api ./elothing-api
            sudo systemctl start elothing-api.service
            sleep 3
            systemctl status elothing-api.service

