name: Deploy to VPS

on:
  push:
    branches: ['master']
    paths: ['backend/**', '.github/workflows/backend.yml']

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - name: Test
        run: |
          zig build test
      - name: Build
        run: |
          zig build --release=fast

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: 'backend/zig-out/bin'

