name: Deploy to VPS

on:
  push:
    branches: ['master']
    paths: ['backend/**', '.github/workflows/backend.yml']

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: |
          zig build test
          zig build --release=fast

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'frontend/build/'

